[site]
title = "Muyang Lyu"
description = "PhD student at Peking University."
favicon = "/favicon.svg"
last_updated = "May 22, 2026"

[author]
name = "Muyang Lyu (吕沐洋)"
title = "Ph.D. Candidate"
institution = "Peking University"
avatar = "/bio.png"

[social]
# Contact information (leave blank or delete to hide)

email = "lyumuyang@stu.pku.edu.cn"
# location = "Beijing, China"
# location_details = ["No.5 Yiheyuan Road, Haidian District, Beijing 100871, P.R.China"]

google_scholar = "https://scholar.google.com/citations?user=pdp7LlwAAAAJ"
# orcid = "https://orcid.org/0009-0002-5138-3155"
cv_pdf = "/cv.pdf"
github = "https://github.com/senngadaisuki"
x = "https://x.com/lyu_muyang"
linkedin = "https://www.linkedin.com/in/muyanglyu/"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = false
locales = ["en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale
mode = "fixed"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = false
# Show a language switcher on the top right corner
switcher = false

[i18n.labels]
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
