[[items]]
period = "2023 - 2028 (expected)"
school = "Peking University"
degree = "Ph.D. in Integrated Life Sciences (Physics)"
details = ["Supervisor: Prof. Si Wu"]

[[items]]
period = "2019 - 2023"
school = "Beijing Normal University"
degree = "B.Sc. in Computer Science and Technology"
